before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
sudo: false
otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3
script:
  - ./rebar3 do xref,eunit,dialyzer,coveralls send
